#!/bin/bash

urls=()

# Prompt the user to enter the URLs
while true; do
    read -p "Enter a URL (or 'q' to quit): " url
    if [[ $url == "q" ]]; then
        break
    fi
    urls+=("$url")
done

# Download HTML files using wget
for url in "${urls[@]}"; do
    output_file=$(echo "$url" | sed -e 's#https://##' -e 's#http://##' -e 's#/#_#g').html
    wget -O "$output_file" "$url"
    echo "Downloaded $url as $output_file"
done
